# Codex MCP config - avvia i server tramite docker compose (stdio)

[mcp_servers."github-project-manager"]
command = "docker"
args = [
  "compose",
  "-f", "${workspaceFolder}/docker/mcp/docker-compose.yml",
  "--project-directory", "${workspaceFolder}/docker/mcp",
  "run", "--rm", "--no-deps",
  "github-project-manager",
]

[mcp_servers."memory-bank"]
command = "docker"
args = [
  "compose",
  "-f", "${workspaceFolder}/docker/mcp/docker-compose.yml",
  "--project-directory", "${workspaceFolder}/docker/mcp",
  "run", "--rm", "--no-deps",
  "memory-bank",
]

[mcp_servers."sequential"]
command = "docker"
args = [
  "compose",
  "-f", "${workspaceFolder}/docker/mcp/docker-compose.yml",
  "--project-directory", "${workspaceFolder}/docker/mcp",
  "run", "--rm", "--no-deps",
  "sequential",
]

[mcp_servers."playwright"]
command = "docker"
args = [
  "compose",
  "-f", "${workspaceFolder}/docker/mcp/docker-compose.yml",
  "--project-directory", "${workspaceFolder}/docker/mcp",
  "run", "--rm", "--no-deps",
  "playwright",
]

[mcp_servers."magic"]
command = "docker"
args = [
  "compose",
  "-f", "${workspaceFolder}/docker/mcp/docker-compose.yml",
  "--project-directory", "${workspaceFolder}/docker/mcp",
  "run", "--rm", "--no-deps",
  "magic",
]

[mcp_servers."claude-context"]
command = "docker"
args = [
  "compose",
  "-f", "${workspaceFolder}/docker/mcp/docker-compose.yml",
  "--project-directory", "${workspaceFolder}/docker/mcp",
  "run", "--rm", "--no-deps",
  "claude-context",
]

[mcp_servers."knowledge-graph"]
command = "docker"
args = [
  "compose",
  "-f", "${workspaceFolder}/docker/mcp/docker-compose.yml",
  "--project-directory", "${workspaceFolder}/docker/mcp",
  "run", "--rm", "--no-deps",
  "knowledge-graph",
]

[mcp_servers."n8n"]
command = "docker"
args = [
  "compose",
  "-f", "${workspaceFolder}/docker/mcp/docker-compose.yml",
  "--project-directory", "${workspaceFolder}/docker/mcp",
  "run", "--rm", "--no-deps",
  "n8n-manager",
]

[mcp_servers."aakarsh-sasi-memory-bank-mcp"]
command = "npx"
args = ["-y", "@allpepper/memory-bank-mcp@latest"]
env = { MEMORY_BANK_ROOT = "${workspaceFolder}/mcp/memory-bank/storage" }

# === MCP Kit Wrappers (Simple STDIO approach) ===
# These use PowerShell wrappers from tools/mcp-kit/wrappers/
# Lightweight, portable, ideal for quick start and cross-repo replication

[mcp_servers.github]
command = "powershell"
args = [
  "-NoProfile",
  "-ExecutionPolicy", "Bypass",
  "-File", "${workspaceFolder}/tools/mcp-kit/wrappers/github-mcp.ps1"
]
