services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_HOST=localhost
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_SECURE_COOKIE=false
      # Vars used by workflow templates
      - API_BASE_URL=${API_BASE_URL:-http://api:3001}
      - API_TOKEN=${API_TOKEN:-dev-token}
    ports:
      - "5678:5678"
    volumes:
      - ../apps/n8n:/home/node/.n8n
    depends_on:
      - api

