name: Create Issues from YAML
on:
  push:
    branches: [ "backlog/auto" ]
    paths: [ "backlog/issues.yaml" ]

jobs:
  create:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: mikefarah/yq@v4
      - run: |
          bash tools/create_issues.sh backlog/issues.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
