name: E2E - Puppeteer MCV

on:
  pull_request:
    branches: [develop, main]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml

      - name: Enable Corepack and pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.17.1 --activate

      - name: Install workspace dependencies
        run: pnpm -w install --frozen-lockfile

      - name: Install Chrome for Puppeteer
        run: pnpm --filter "@influencerai/e2e" exec puppeteer browsers install chrome

      - name: Launch MCV server
        run: |
          pnpm --filter "@influencerai/e2e" run e2e:server > server.log 2>&1 &

      - name: Wait for health endpoint
        run: pnpm --filter "@influencerai/e2e" exec wait-on http-get://localhost:5173/healthz

      - name: Run E2E tests (Puppeteer)
        env:
          E2E_BASE: http://localhost:5173
        run: pnpm --filter "@influencerai/e2e" run e2e:test

      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-logs
          path: server.log
