name: Update Issue Checklist on PR Merge

on:
  pull_request:
    types: [closed]

permissions:
  contents: read
  issues: write
  pull-requests: read

jobs:
  update-checklist:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Mark linked issue checkboxes as completed
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            // Fetch issues closed by this PR via GraphQL (closingIssuesReferences)
            const query = `
              query($owner:String!, $repo:String!, $number:Int!) {
                repository(owner:$owner, name:$repo) {
                  pullRequest(number:$number) {
                    closingIssuesReferences(first: 20) {
                      nodes { number title body }
                    }
                  }
                }
              }
            `;
            const result = await github.graphql(query, { owner, repo, number: prNumber });
            const nodes = result.repository.pullRequest.closingIssuesReferences.nodes || [];

            if (nodes.length === 0) {
              core.info('No linked closing issues found for this PR.');
              return;
            }

            for (const issue of nodes) {
              const original = issue.body || '';
              const updated = original.replace(/^- \[ \] /gm, '- [x] ');
              if (updated !== original) {
                await github.rest.issues.update({
                  owner,
                  repo,
                  issue_number: issue.number,
                  body: updated,
                });
                core.info(`Updated checklist for issue #${issue.number} (${issue.title})`);
              } else {
                core.info(`No unchecked boxes to update for issue #${issue.number}`);
              }
            }

